### ISSUE TITLE
Question - Could <a> tag be a menuitem as well?

### ISSUE THREAD

**Issue by Stanko** [Heydon/inclusive-menu-button#45]
Hello,
First, I want to thank you for the great little library you made!

I have one question, and I'm not sure if this is going to break aria compliance.

Could `a` tag be used along with `button` for menu items? I want to use it for language selector, and it that scenario it makes more sense for items to be links.

I just changed this line:

https://github.com/Heydon/inclusive-menu-button/blob/218114116595ef5c31aca24a533b5e0ddd4442cf/inclusive-menu-button.js#L47

to:

```js
 this.menuItems = this.menu.querySelectorAll('button,a');
```

and everything seems to work.

If you think this is a reasonable change, I can make a quick PR.

Cheers!

**Comment by Heydon** [comment]
Hi @Stanko,

The reason it does not use links is because the `menuitem` role will override the link role, and the link will therefore behave in an unexpected way. 

I have tried to strictly follow standards for menu buttons here, so only include button-like `menuitem` controls. I do not see much harm in doing as you suggest (aside from what I've already noted), but please fork instead. The reason is, this library is cited in a print book and should behave as it was originally intended (since sold copies of the book can't be updated).

Cheers

**Comment by Stanko** [comment]
That makes sense. I wanted to check before using a fork.

Thank you!
